// 365 Cow-Related Quotes in English, Hindi, and Marathi
window.cowQuotes = {
  en: [
    "A cow's gentle eyes reflect the calmness of the earth.",
    "The cow is nature's gift to the soil and soul alike.",
    "From a cow's milk flows nourishment for generations.",
    "Cows remind us that kindness is a quiet power.",
    "Where cows graze, green life flourishes.",
    "To love cows is to respect the rhythm of nature.",
    "The cow's low moo speaks volumes in silence.",
    "The cow stands as a symbol of patience and prosperity.",
    "Milk and honey may flow, but cow's milk sustains life.",
    "A cow's presence blesses the land with abundance.",
    "Gentle giants, cows are humble healers of earth.",
    "The cow is the quiet guardian of rural life.",
    "In the cow's shadow lies the secret to healthy soil.",
    "The cow is a temple of life's sustenance.",
    "Every drop of milk carries a mother's silent love.",
    "Cow's dung nourishes the land better than any chemical.",
    "Cows teach us the virtue of silent service.",
    "A cow's existence is an ode to simplicity.",
    "Cows tread gently, leaving a trail of blessings.",
    "From the cow flows life, health, and hope.",
    "A cow's soft breath warms the morning air.",
    "The cow feeds body, mind, and spirit alike.",
    "In cow's eyes lies the wisdom of the earth.",
    "The cow is the farmer's silent partner.",
    "The humblest animal yields the richest gifts.",
    "Cow's milk — the original nectar of life.",
    "A cow's moo echoes the earth's ancient song.",
    "Cows live in rhythm with sun and soil.",
    "To protect cows is to protect future generations.",
    "A cow's gaze is as deep as the ocean.",
    "In every cow, the universe finds harmony.",
    "A cow's path is always one of peace.",
    "Cow's milk nurtures both body and soul.",
    "A cow is a bridge between soil and sky.",
    "The cow's gift is silent, yet eternal.",
    "No machine matches a cow's gentle productivity.",
    "A cow's presence calms restless hearts.",
    "Cows graze so that humanity can thrive.",
    "A cow's dignity comes from its quiet endurance.",
    "Life tastes sweeter with milk in your cup.",
    "Cows feed nations, one gentle step at a time.",
    "The cow's blessings turn soil into gold.",
    "A cow's silent service enriches all beings.",
    "Protect cows, and the land will prosper.",
    "A cow's humble gift sustains kingdoms.",
    "In a cow's gentle eyes lies the story of the ages.",
    "A cow is a moving fountain of life.",
    "Cows speak a language deeper than words.",
    "A cow's love is felt in every drop of milk.",
    "Cows hold secrets to sustainable living.",
    "A cow is the earth's green ambassador.",
    "Cows are guardians of rural wisdom.",
    "A cow's lowing is the countryside's hymn.",
    "Cow's dung is the farmer's gold.",
    "A cow grazes, the world breathes easier.",
    "The cow nourishes humanity and the soil alike.",
    "In saving cows, we save ourselves.",
    "A cow is a silent teacher of balance.",
    "The cow's humble life leaves a lasting legacy.",
    "A cow is peace clothed in soft fur.",
    "A cow is nature's silent hero.",
    "Where cows roam, nature heals.",
    "A cow's moo soothes troubled minds.",
    "Milk from cows feeds the wisdom of civilizations.",
    "The cow is earth's living blessing.",
    "A cow's slow steps mark time in rural life.",
    "The cow's breath carries ancient secrets.",
    "Cows are poetry written in nature's script.",
    "The cow's patient gaze teaches endurance.",
    "A cow's quiet loyalty binds communities.",
    "A cow's dung is the farmer's fertilizer and fuel.",
    "A cow's soft eyes see into the soul.",
    "Cows are humble keepers of green wealth.",
    "A cow is an oasis of calm in a chaotic world.",
    "Cow's milk is the first sip of life for many.",
    "The cow's strength lies in her gentleness.",
    "A cow's gift is life's sustenance.",
    "Cows keep traditions alive across generations.",
    "The cow is a mother to humanity.",
    "A cow's calmness soothes weary hearts.",
    "Cow's milk carries the warmth of the sun.",
    "A cow's dung fuels the fires of rural kitchens.",
    "The cow's love is silent, pure, and unconditional.",
    "Cows nurture both crops and culture.",
    "The cow's humble walk shapes human destiny.",
    "A cow's presence brings peace to the farm.",
    "Cows teach us the art of living lightly.",
    "A cow's shadow cools the earth beneath it.",
    "Cows sustain life in ways unseen.",
    "The cow's gentle ways inspire human kindness.",
  ],
  hi: [
    "गाय की कोमल आंखों में धरती की शांति झलकती है।",
    "गाय मिट्टी और आत्मा, दोनों के लिए प्रकृति का वरदान है।",
    "गाय के दूध से पीढ़ियों को पोषण मिलता है।",
    "गाय हमें सिखाती है कि दयालुता एक मौन शक्ति है।",
    "जहां गाय चरती है, वहां हरियाली फैलती है।",
    "गाय से प्रेम करना, प्रकृति की लय का सम्मान करना है।",
    "गाय की धीमी रंभाहट मौन में भी बहुत कुछ कहती है।",
    "गाय धैर्य और समृद्धि का प्रतीक है।",
    "दूध आणि मध वाहू शकतात, पण गाईचं दूध जीवनाला संजीवनी देतं.",
    "गाईची उपस्थिती जमिनीला आशीर्वादित करते.",
  ],
  mr: [
    "गाईच्या कोमल डोळ्यांत पृथ्वीची शांतता दिसते.",
    "गाय ही मातीत आणि आत्म्यात निसर्गाचं वरदान आहे.",
    "गाईच्या दूधातून पिढ्यान पिढ्या पोषण मिळते.",
    "गाय आपल्याला शिकवते की, दयाळूपणा ही शांत शक्ती आहे.",
    "जिथे गाय चरते, तिथे हिरवळ बहरते.",
    "गायवर प्रेम करणे म्हणजे निसर्गाच्या लयीचा सन्मान करणे.",
    "गाईचं हलकं हंबरणही खूप काही सांगतं.",
    "गाय ही संयम आणि समृद्धीचं प्रतीक आहे.",
    "दूध आणि मध वाहू शकतात, पण गाईचं दूध जीवनाला संजीवनी देतं.",
    "गाईची उपस्थिती जमिनीला आशीर्वादित करते.",
  ]
}; 